"""Initial migration

Revision ID: 8bb87dd0fcdc
Revises: fd5ffc30415d
Create Date: 2024-12-11 17:05:00.122964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb87dd0fcdc'
down_revision: Union[str, None] = 'fd5ffc30415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examples', sa.Column('description2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examples', 'description2')
    # ### end Alembic commands ###
